// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM0HGLBt_OsQVokXf2rp8J-yqjm2ZU_oo',
    appId: '1:349447263053:web:d4e36fd83683f2c3c29d04',
    messagingSenderId: '349447263053',
    projectId: 'peoplecounting-e8ddf',
    authDomain: 'peoplecounting-e8ddf.firebaseapp.com',
    databaseURL: 'https://peoplecounting-e8ddf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'peoplecounting-e8ddf.firebasestorage.app',
    measurementId: 'G-XC0ZBCYTB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4NngCv_KkpQr0lIcL38RfYp8a3D-AgAE',
    appId: '1:349447263053:android:5e0798cbca902f0ac29d04',
    messagingSenderId: '349447263053',
    projectId: 'peoplecounting-e8ddf',
    databaseURL: 'https://peoplecounting-e8ddf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'peoplecounting-e8ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUy_Z0nY11QghZaVQcjqeHz7bLvCOKAC8',
    appId: '1:349447263053:ios:fbd2928fe8b1fbbec29d04',
    messagingSenderId: '349447263053',
    projectId: 'peoplecounting-e8ddf',
    databaseURL: 'https://peoplecounting-e8ddf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'peoplecounting-e8ddf.firebasestorage.app',
    iosBundleId: 'com.example.newaplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUy_Z0nY11QghZaVQcjqeHz7bLvCOKAC8',
    appId: '1:349447263053:ios:fbd2928fe8b1fbbec29d04',
    messagingSenderId: '349447263053',
    projectId: 'peoplecounting-e8ddf',
    databaseURL: 'https://peoplecounting-e8ddf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'peoplecounting-e8ddf.firebasestorage.app',
    iosBundleId: 'com.example.newaplikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM0HGLBt_OsQVokXf2rp8J-yqjm2ZU_oo',
    appId: '1:349447263053:web:5955cfa3cb31f541c29d04',
    messagingSenderId: '349447263053',
    projectId: 'peoplecounting-e8ddf',
    authDomain: 'peoplecounting-e8ddf.firebaseapp.com',
    databaseURL: 'https://peoplecounting-e8ddf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'peoplecounting-e8ddf.firebasestorage.app',
    measurementId: 'G-V8W17EE32R',
  );

}